# Generated by Django 3.2 on 2022-11-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0007_delete_aimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('input_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('checkbox', models.BooleanField(default=0)),
            ],
        ),
    ]
