# Generated by Django 3.2 on 2022-11-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0008_aimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='correct_count',
            new_name='answer_count',
        ),
        migrations.RenameField(
            model_name='aimodel',
            old_name='input_count',
            new_name='prediction_count',
        ),
    ]
