# Generated by Django 3.2 on 2022-11-22 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0008_aimodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
