# Generated by Django 3.2 on 2022-11-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0009_auto_20221122_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='model',
            new_name='file',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='checkbox',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='input_count',
            field=models.IntegerField(default=0),
        ),
    ]
