# Generated by Django 3.2 on 2022-11-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0010_auto_20221122_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='checkbox',
            new_name='is_using',
        ),
    ]
