# Generated by Django 3.2 on 2022-11-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0012_aimodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
