# Generated by Django 3.2 on 2022-11-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0009_auto_20221122_1424'),
        ('signlanguage', '0013_alter_aimodel_name'),
    ]

    operations = [
    ]
