# Generated by Django 3.2 on 2022-11-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0014_merge_0009_auto_20221122_1424_0013_alter_aimodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\minor\\Desktop\\coda-team\\KT_mini_proj7\\mini_proj\\signlanguage/model'),
        ),
    ]
