# Generated by Django 3.2 on 2022-11-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0015_alter_aimodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
